### ISSUE TITLE
Cannot migrate from 4.2.0

### ISSUE THREAD

**Issue by swiffer** [crater-invoice/crater#603]
**Describe the bug**
Tried to update to 5.0.0

**Expected behavior**
Migrating: 2021_06_30_062411_update_customer_id_in_all_tables

   BadMethodCallException

  Call to undefined method Crater\Models\User::addresses()

  at vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:71
     67▕      * @throws \BadMethodCallException
     68▕      */
     69▕     protected static function throwBadMethodCallException($method)
     70▕     {
  ➜  71▕         throw new BadMethodCallException(sprintf(
     72▕             'Call to undefined method %s::%s()', static::class, $method
     73▕         ));
     74▕     }
     75▕ }

  • Bad Method Call: Did you mean Crater\Models\User::deleteUsers() ?

      +2 vendor frames
  3   database/migrations/2021_06_30_062411_update_customer_id_in_all_tables.php:44
      Illuminate\Database\Eloquent\Model::__call()

      +21 vendor frames
  25  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

**Screenshots**

**Please complete the following information:**
- Crater version: 
- PHP version: 
- Database type and version: 

**Optional info**
- OS:  [e.g. Ubuntu]
- Browser: [e.g. chrome, safari]

**Comment by swiffer** [comment]
@mohitpanjwani - see you are already working on it - is a new release tagged when solved ? this happened in one of my projects in the past as well - started to avoid using app code in the migration so migrations still run fine when the app changes over time

**Comment by swiffer** [comment]
So i think the issue is that the migration file is trying to access the user address which is no longer part of the user model - i added this to the user model temporarly and migration run through:

    public function addresses()
    {
        return $this->hasMany(Address::class);
    }

**Comment by swiffer** [comment]
additionally customer_id was not seed in invoices and expenses in my case so later

2021_11_13_114808_calculate_base_values_for_existing_data

failed to set base values. maybe worth checking this again as well.

**Comment by mohitpanjwani** [comment]
Hey man! Thank you for the patience and the details. 

We were working on this as soon as we received the feedback. I pushed a commit to fix this last. 

Does it work for you now? I will take a look tomorrow if there’s anything else.

**Comment by mohitpanjwani** [comment]
> additionally customer_id was not seed in invoices and expenses in my case so later
> 
> 2021_11_13_114808_calculate_base_values_for_existing_data
> 
> failed to set base values. maybe worth checking this again as well.

Yes exactly. After testing the update about a million times. There a last minute fix which caused this issue.

**Comment by mohitpanjwani** [comment]
Also temporarily there’s an issue with deleting the user coz of this change. We will deploy a fix for that asap on minor release.

**Comment by rundx** [comment]
migration still not working for me on master branch

    
    php artisan migrate
    **************************************
    *     Application In Production!     *
    **************************************
    
     Do you really wish to run this command? (yes/no) [no]:
     > yes
    
    Migrating: 2021_06_28_105334_create_bouncer_tables
    
       Illuminate\Database\QueryException
    
      SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key     constraint fails (SQL: drop table `roles`)
    
      at vendor/laravel/framework/src/Illuminate/Database/Connection.php:703
        699▕         // If an exception occurs when attempting to run a query, we'll format the error
        700▕         // message to include the bindings with SQL, which will make this exception a
        701▕         // lot more helpful to the developer instead of just the database's errors.
        702▕         catch (Exception $e) {
      ➜ 703▕             throw new QueryException(
        704▕                 $query, $this->prepareBindings($bindings), $e
        705▕             );
        706▕         }
        707▕     }
    
          +12 vendor frames
      13  database/migrations/2021_06_28_105334_create_bouncer_tables.php:19
          Illuminate\Support\Facades\Facade::__callStatic()
    
          +21 vendor frames
      35  artisan:37
          Illuminate\Foundation\Console\Kernel::handle()

**Comment by mohitpanjwani** [comment]
> migration still not working for me on master branch
> 
> ```
> php artisan migrate
> **************************************
> *     Application In Production!     *
> **************************************
> 
>  Do you really wish to run this command? (yes/no) [no]:
>  > yes
> 
> Migrating: 2021_06_28_105334_create_bouncer_tables
> 
>    Illuminate\Database\QueryException
> 
>   SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key     constraint fails (SQL: drop table `roles`)
> 
>   at vendor/laravel/framework/src/Illuminate/Database/Connection.php:703
>     699▕         // If an exception occurs when attempting to run a query, we'll format the error
>     700▕         // message to include the bindings with SQL, which will make this exception a
>     701▕         // lot more helpful to the developer instead of just the database's errors.
>     702▕         catch (Exception $e) {
>   ➜ 703▕             throw new QueryException(
>     704▕                 $query, $this->prepareBindings($bindings), $e
>     705▕             );
>     706▕         }
>     707▕     }
> 
>       +12 vendor frames
>   13  database/migrations/2021_06_28_105334_create_bouncer_tables.php:19
>       Illuminate\Support\Facades\Facade::__callStatic()
> 
>       +21 vendor frames
>   35  artisan:37
>       Illuminate\Foundation\Console\Kernel::handle()
> ```

Have you created some roles on the roles table or made some customisations to core? 

Anyhow, can you delete the roles, permissions, role_has_permissions,  model_has_roles & model_has_permissons tables manually and try the migration command again? 

That should fix it.

**Comment by rundx** [comment]
The migration works now but I get this error

`
  [2021-11-30 18:20:18] production.ERROR: The Mix manifest does not exist. (View: 
  /home/****/www/crater/resources/views/app.blade.php) {"view": 
  {"view":"/home/****/www/crater/vendor/laravel/framework/src/Illuminate/Foundation/Mix.php","data": 
  []},"userId":1,"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): The Mix manifest does not 
  exist. (View: /home/****/www/crater/resources/views/app.blade.php) at 
  /home/****/www/crater/vendor/laravel/framework/src/Illuminate/Foundation/Mix.php:52)[2021-11-30 18:20:18] 
  production.ERROR: The Mix manifest does not exist. (View: /home/****/www/crater/resources/views/app.blade.php) 
  {"view":{"view":"/home/****/www/crater/vendor/laravel/framework/src/Illuminate/Foundation/Mix.php","data": 
  []},"userId":1,"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): The Mix manifest does not 
  exist. (View: /home/****/www/crater/resources/views/app.blade.php) at 
  /home/****/www/crater/vendor/laravel/framework/src/Illuminate/Foundation/Mix.php:52)
`

**Comment by kolaente** [comment]
I got that same error message as well but it went away when I ran the migration again. Now I'm getting this:

```
[2021-11-30 19:15:18] production.ERROR: Class 'Predis\Client' not found {"exception":"[object] (Error(code: 0): Class 'Predis\\Client' not found at /var/www/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PredisConnector.php:26)
```

Should I open a new issue for that?

**Comment by mohitpanjwani** [comment]
> I got that same error message as well but it went away when I ran the migration again. Now I'm getting this:
> 
> ```
> [2021-11-30 19:15:18] production.ERROR: Class 'Predis\Client' not found {"exception":"[object] (Error(code: 0): Class 'Predis\\Client' not found at /var/www/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PredisConnector.php:26)
> ```
> 
> Should I open a new issue for that?

Hey, Can you run following command and then see if it works? 
composer require predis/predis`

**Comment by mohitpanjwani** [comment]
> The migration works now but I get 500 Server Error when I load the app I get this error in logs
> 
> `[2021-11-30 18:20:18] production.ERROR: The Mix manifest does not exist. (View: /home/****/www/crater/resources/views/app.blade.php) {"view": {"view":"/home/****/www/crater/vendor/laravel/framework/src/Illuminate/Foundation/Mix.php","data": []},"userId":1,"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): The Mix manifest does not exist. (View: /home/****/www/crater/resources/views/app.blade.php) at /home/****/www/crater/vendor/laravel/framework/src/Illuminate/Foundation/Mix.php:52)`

That's new! We've completely removed laravel-mix from this release and we're using `vite` instead. 

Have you made any changes to the code?

**Comment by rundx** [comment]
No I just copied over .env file and storage dir

    git clone https://github.com/crater-invoice/crater
    cd crater
    cp -f ../crater-backup/.env .
    cp -rf ../crater-backup/storage .

**Comment by kolaente** [comment]
> Hey, Can you run following command and then see if it works?
> composer require predis/predis

@mohitpanjwani That works, thanks. Any reason it is not included in crater's dependencies by default?

**Comment by chestnutbak** [comment]
I'm also getting the "the Mix manifest does not exist." message. How can I fix this if I didn't install using composer and just uploaded the files to my Plesk server... thanks!

**Comment by jsargent8789** [comment]
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'slug' (SQL: alter table `companies` add `slug` varchar(255) null, add `owner_id` int unsigned null)

I can't update to 5.0.3

**Comment by jsargent8789** [comment]
I tried to reinstall and still get these errors my mysql

**Comment by mohitpanjwani** [comment]
> I'm also getting the "the Mix manifest does not exist." message. Anybody have a fix for this yet?

This should no longer be an issue on 5.0.3. 

Please update and let me know if this still happens. Also please run `php artisan optimize:clear` if you still encounter this error.
